#ifndef ERRORS_H
#define ERRORS_H

#define ERR_INVALID_FORMAT -1
#define ERR_SURNAME_NOT_SPECIFIED -2
#define ERR_NAME_NOT_SPECIFIED -3
#define ERR_AGE_NOT_SPECIFIED -4
#define ERR_RACE_NOT_SPECIFIED -5
#define ERR_CITY_NOT_SPECIFIED -6
#define ERR_FELONY_AGE_NOT_SPECIFIED -7
#define ERR_INVALID_AGE -8
#define ERR_INVALID_FELONY_AGE -9
#define ERR_INVALID_EDUCATION -10
#define ERR_INVALID_M_VICTIMS -11
#define ERR_INVALID_F_VICTIMS -12
#define ERR_INVALID_NUM_VICTIMS -13
#define ERR_INVALID_TOTAL_VICTIMS -14
#define ERR_FILE_NOT_FOUND -15
#define SUCCESS 1
#define RESULT_NOTHING_TO_SAVE 2
#define RESULT_NO_ENTRIES 3
#define ERR_INVALID_COMMAND -16
#define ERR_INVALID_ARGS -17
#define ERR_NO_MATCHES_FOUND -18

#define REPORT_NA -1


const char *err_to_str(int err);

#endif
